<a href="https://colab.research.google.com/github/ferrydrn/skripsi-regresi/blob/main/skripsi_hitung_regresi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np
import statsmodels.api as sm
from sklearn.linear_model import LinearRegression

In [8]:
# Baca file Excel
data = pd.read_excel('test.xlsx')

In [9]:
print(data)

   periklanan  pemasaran_langsung  penjualan_personal  penjualan
0     3000000             4000000             3000000  412163500
1     3000000             5000000             2000000  436407000
2     3000000             4500000             3000000  414113500
3     2000000             6000000             2000000  468905500
4     2500000             6500000             1000000  871604100
5     3000000             5000000             2000000  765510575
6     2000000             6000000             2000000  774170075
7     2500000             5500000             2000000  752243450


In [10]:
# Variabel tetap (y) dan variabel bebas (x1, x2, x3)
y = data['penjualan'].values
X = data[['periklanan', 'pemasaran_langsung', 'penjualan_personal']].values

In [11]:
# Tambahkan kolom konstanta pada variabel bebas
X = sm.add_constant(X)

In [12]:
data = data.dropna(subset=['periklanan', 'pemasaran_langsung', 'penjualan_personal', 'penjualan'])

In [13]:
# Buat model regresi linear berganda
model = sm.OLS(y, X)

In [14]:
# Latih model
result = model.fit()

In [15]:
# Koefisien regresi
coefficients = result.params
print("Koefisien regresi:")
print(coefficients)

Koefisien regresi:
[ 9.98637174e+08 -4.25075410e+00  1.38425967e+01 -2.11354366e+02]


In [16]:
# Korelasi
correlation_matrix = data[['penjualan', 'periklanan', 'pemasaran_langsung', 'penjualan_personal']].corr()
print("Korelasi:")
print(correlation_matrix)

Korelasi:
                    penjualan  periklanan  pemasaran_langsung  \
penjualan            1.000000   -0.361762            0.674749   
periklanan          -0.361762    1.000000           -0.789076   
pemasaran_langsung   0.674749   -0.789076            1.000000   
penjualan_personal  -0.749663    0.440086           -0.876422   

                    penjualan_personal  
penjualan                    -0.749663  
periklanan                    0.440086  
pemasaran_langsung           -0.876422  
penjualan_personal            1.000000  


In [17]:
# Determinasi
r_squared = result.rsquared
print("Koefisien determinasi (R-squared):")
print(r_squared)

Koefisien determinasi (R-squared):
0.5633597485855208


In [18]:
# Uji F
f_value = result.fvalue
f_pvalue = result.f_pvalue
print("Uji F:")
print("F-value:", f_value)
print("P-value:", f_pvalue)

Uji F:
F-value: 1.720286503624098
P-value: 0.3002122733371877


In [19]:
# Uji t
t_values = result.tvalues
t_pvalues = result.pvalues
print("Uji t:")
print("T-values:")
print(t_values)
print("P-values:")
print(t_pvalues)

Uji t:
T-values:
[ 0.23345102 -0.00943827  0.03133264 -0.53194128]
P-values:
[0.82687166 0.99292143 0.97650533 0.62293881]


In [20]:
# Prediksi berdasarkan model
y_pred = result.predict(X)
data['Prediksi'] = y_pred

In [21]:
# Menampilkan data beserta prediksi
print(data)

   periklanan  pemasaran_langsung  penjualan_personal  penjualan      Prediksi
0     3000000             4000000             3000000  412163500  4.071922e+08
1     3000000             5000000             2000000  436407000  6.323892e+08
2     3000000             4500000             3000000  414113500  4.141135e+08
3     2000000             6000000             2000000  468905500  6.504825e+08
4     2500000             6500000             1000000  871604100  8.666328e+08
5     3000000             5000000             2000000  765510575  6.323892e+08
6     2000000             6000000             2000000  774170075  6.504825e+08
7     2500000             5500000             2000000  752243450  6.414358e+08


In [22]:
# Menampilkan rekomendasi
threshold = 0.5  # Ubah threshold sesuai kebutuhan
rekomendasi = data[data['Prediksi'] > threshold]
print("Rekomendasi:")
print(rekomendasi)

Rekomendasi:
   periklanan  pemasaran_langsung  penjualan_personal  penjualan      Prediksi
0     3000000             4000000             3000000  412163500  4.071922e+08
1     3000000             5000000             2000000  436407000  6.323892e+08
2     3000000             4500000             3000000  414113500  4.141135e+08
3     2000000             6000000             2000000  468905500  6.504825e+08
4     2500000             6500000             1000000  871604100  8.666328e+08
5     3000000             5000000             2000000  765510575  6.323892e+08
6     2000000             6000000             2000000  774170075  6.504825e+08
7     2500000             5500000             2000000  752243450  6.414358e+08


In [59]:
thitung = t_values
ttabel = 2.776
signifikansi = t_pvalues

def jadikan_ttabel_negatif(ttabel, thitung):
    return -ttabel if thitung < 0 else ttabel

def uji_pengaruh(thitung, ttabel, signifikansi):
    if signifikansi > 0.05 and abs(thitung) > ttabel:
        return "Pengaruh variabel tersebut berpengaruh namun tidak signifikan terhadap volume penjualan."
    else:
        return "Pengaruh variabel tersebut tidak berpengaruh atau tidak signifikan terhadap volume penjualan."

ttabel_periklanan = jadikan_ttabel_negatif(ttabel, thitung[1])
hasil_uji_periklanan = uji_pengaruh(thitung[1], ttabel_periklanan, signifikansi[1])
print("Pengaruh periklanan terhadap volume penjualan:", hasil_uji_periklanan)

ttabel_pemasaran_langsung = jadikan_ttabel_negatif(ttabel, thitung[2])
hasil_uji_pemasaran_langsung = uji_pengaruh(thitung[2], ttabel_pemasaran_langsung, signifikansi[2])
print("Pengaruh pemasaran langsung terhadap volume penjualan:", hasil_uji_pemasaran_langsung)

ttabel_penjualan_personal = jadikan_ttabel_negatif(ttabel, thitung[3])
hasil_uji_penjualan_personal = uji_pengaruh(thitung[3], ttabel_penjualan_personal, signifikansi[3])
print("Pengaruh penjualan personal terhadap volume penjualan:", hasil_uji_penjualan_personal)


Pengaruh periklanan terhadap volume penjualan: Pengaruh variabel tersebut berpengaruh namun tidak signifikan terhadap volume penjualan.
Pengaruh pemasaran langsung terhadap volume penjualan: Pengaruh variabel tersebut tidak berpengaruh atau tidak signifikan terhadap volume penjualan.
Pengaruh penjualan personal terhadap volume penjualan: Pengaruh variabel tersebut berpengaruh namun tidak signifikan terhadap volume penjualan.
